Paciente8159/uCNC

- uCNC/cnc.c
- uCNC/parser.c
-fixed jog state stayed active after the motion finished
-unable to send a new jog command in JOG state. (only possible in IDLE mode)
> Fix JOG related commands

- uCNC/interpolator.c
- fix prescaller variable size that caused unintended rewriting of next_dss value when calculating timer counter and prescaller
- changed names of timer counter and prescaller to be easier to understand
> Fix Dynamic Step Spread

- uCNC/interpolator.c
- uCNC/parser.c
- uCNC/planner.c
- uCNC/protocol.c
- uCNC/settings.c
- uCNC/settings.h
Implement laser mode compliant to Grbl includes:
- laser mode activation via parameter `$32`
- fixed power laser mode via `M3`
- dynamic power laser mode via command `M4`
- laser only active on `G1`, `G2` and `G3` commands
- laser auto turn off when motion stops
> improve laser mode

- uCNC/config.h
- uCNC/grbl_interface.h
-added configurable Grbl startup message emulation (compatibility mode). Some Grbl applications expect to get the "Grbl 1.x" message to recognize the device.
> Added Grbl startup emulation message

- makefiles/avr/makefile
- makefiles/stm32f103/Makefile
- src/cnc.c
- src/hal/mcus/avr/mcu_avr.c
- src/hal/mcus/avr/mcumap_avr.h
- src/hal/mcus/mcu.h
- src/hal/mcus/stm32f10x/mcu_stm32f10x.c
- src/hal/mcus/stm32f10x/mcumap_stm32f10x.h
- src/hal/mcus/virtual/mcu_virtual.c
- src/hal/mcus/virtual/mcumap_virtual.h
- src/interface/grbl_interface.h
- src/interface/serial.c
- src/interface/serial.h
-removed unneeded volatile attributes of some variables
-optimization for synchronous serial TX with direct serial output without buffer
-modified HAL for MCU for both serial TX and RX
-TX ISR must now disabled before putc. MCU putc enables ISR everytime.
-added initial NULL char sending after configuration of UART to force TXE hardware set for STM32
-deleted duplicate SYNC TX config for STM32
> Sync serial optimization

- makefiles/stm32f103/Makefile
- src/hal/mcus/stm32f10x/mcumap_stm32f10x.h
- tinyusb/README.md
-function calls to check if write/read chars were available were pointing to static inline only visible within the same compilation unit) versions of the library and causing the build to fail.
-small update to tinyUSB readme file
> stm32 tinyusb functions fix

- src/cnc.c
- src/cnc.h
- src/core/interpolator.c
- src/core/interpolator.h
- src/core/io_control.c
- src/core/motion_control.c
- src/core/motion_control.h
- src/core/parser.c
- src/core/planner.c
- src/core/planner.h
- src/hal/mcus/mcu.h
- src/hal/mcus/virtual/mcu_virtual.c
- src/hal/mcus/virtual/mcumap_virtual.h
- src/interface/grbl_interface.h
- src/interface/protocol.c
-moved delay from mcu to cnc to allow cnc tasks to run will in the delay loop
-removed all non motion gcodes and actions from pipeline. These are now executed at the motion control level. This lead to a small code footprint reduction.
-non motion or sync actions now cause the planner and interpolation to get empty before executing.
-delay on resume now working properly though it needs improving
-changed virtual mcu to support these changes (stalled on delays)
-internal alarms renaming and reworking
-reviewed interlocking to reduce code size
-reviewed alarm code flow
-modified reset loop condition checking. If kill condition is not enforced (emergency stop), allows reset.
-replaced Abort (non Grbl) state by Alarm (Grbl) to improve software compatibility
-fixed limit switch condition …
> Redesign sync motions and alarm status communications

- src/cnc.c
- src/cnc.h
- src/core/interpolator.c
- src/core/io_control.c
- src/core/io_control.h
- src/core/motion_control.c
- src/core/parser.c
- src/core/parser.h
- src/core/planner.c
- src/interface/grbl_interface.h
- src/interface/protocol.c
- src/interface/protocol.h
- src/interface/serial.c
-complete alarm and interlocking revision
-added ALARM -1 for emergency stop button press
-only hard/soft limit alarms now force reset like defined by Grbl
-startup blocks blocks will now only run on the first successful unlock after a reset to prevent unwanted startup block calls
-fixed step enabling logic (negative logic)
-stepper enabling now only happens after correct reset
-recoded homing and probe to match interlocking changes
-fixed after homing axis drifting on motions before first specific axis coordinate is set
-fixed hidden probe report alarm (only showed if other input pin alarms were active)
-fixed probing coordinates storing (was saving step count and not machine coordinates)
> Improved alarm interlocking

- src/hal/mcus/stm32f10x/mcu_stm32f10x.c
- src/interface/protocol.c
- src/interface/serial.c
- tinyusb/src/tusb_config.h
-STM32 EEPROM in flash unwritten values are read 0xFF. This causes startup blocks to be read incorrectly. Filters ascii between 0 and 127 to prevent errors.
> fixes startup blocks on STM32

- CHANGELOG.md
- README.md
- makefiles/samd21/Makefile
- src/cnc.c
- src/cnc_build.h
- src/cnc_config.h
- src/hal/boards/samd21/boardmap_mzero.h
- src/hal/boards/samd21/boardmap_zero.h
- src/hal/mcus/samd21/mcu_samd21.c
- src/hal/mcus/samd21/mcumap_samd21.h
- src/hal/mcus/stm32f10x/mcu_stm32f10x.c
- implemented Hardware UART in SAMD21
- modified some NVIC IRQ and global interrupt enable and disable inside ISR code in STM32 and SAMD21
- modified RTC to prevent reentrancy inside ISR code in STM32 and SAMD21
- fixed issue with active CS_RES input that caused resume condition (delay) without active hold present
> samd21 hardware UART implemented

- src/cnc.c
-removed flag that cause interference in soft reset messages (used by applications to talk to Grbl)
> Soft reset not sending welcome message

- CHANGELOG.md
- src/cnc.c
- src/cnc.h
- src/core/utils.h
- src/hal/mcus/avr/mcu_avr.c
- src/hal/mcus/avr/mcumap_avr.h
- src/hal/mcus/samd21/mcu_samd21.c
- src/hal/mcus/samd21/mcumap_samd21.h
- src/hal/mcus/stm32f10x/mcu_stm32f10x.c
- src/hal/mcus/stm32f10x/mcumap_stm32f10x.h
- src/modules/pid_controller.c
- src/modules/pid_controller.h
-moved RTC function to cnc compilation unit. This keeps the code more uniform since implementation is done in a hardware agnostic compilation unit
-small atomic block fixes for STM32 and SAMD21 (uses internal flag to keep state of global interrupts)
-pid function renaming
> moved RTC function to cnc compilation unit and small atomic block fixes

- CHANGELOG.md
- uCNC/src/core/interpolator.c
- fixed interpolator speed calculations for slow movements with instant max speed that and speed was set to 0
> No acceleration for slow motions

- CHANGELOG.md
- uCNC/src/core/parser.c
- uCNC/src/core/utils.h
- uCNC/src/hal/tools/tool.c
- uCNC/src/interface/protocol.c
- uCNC/src/interface/settings.c
- uCNC/src/interface/settings.h
- modified removed `G43.1` command and added `G43` command has defined in the RS274NGC. A similar command to previous `G43.1` is possible with `G43 Z<value>`
- added configurable default loading tool and tools offset
> modified tool length compensation gcode

- CHANGELOG.md
- makefiles/virtual/virtualserial.c
- uCNC/src/cnc.c
- uCNC/src/cnc.h
- uCNC/src/core/motion_control.c
- uCNC/src/hal/mcus/virtual/mcu_virtual.c
- uCNC/src/interface/protocol.c
- modified alarm locking and report messages on alarm status. Soft stop alarm require unlock only. Hard stops will cause soft reset on unlock
- fixed check mode position update of motion control preventing invalid target errors
- fixed sticky check mode even after soft-reset
> Alternative/modified CNC alarm lock

- CHANGELOG.md
- uCNC/src/cnc.c
- uCNC/src/core/interpolator.c
- uCNC/src/core/motion_control.c
- uCNC/src/core/parser.c
- uCNC/src/core/parser.h
- uCNC/src/hal/boards/samd21/boardmap_zero.h
-partially reverted modifications (#98) and (#84) that caused the the machine real position to diverge due to error accumulation with G91 (relative distance) active and also caused bresenham algorith errors
> G91 cumulative error position

- CHANGELOG.md
- uCNC/src/cnc.c
- uCNC/src/cnc.h
- uCNC/src/interface/protocol.c
- uCNC/src/interface/protocol.h
- cnc delay will be executed without exit even if there is an fault condition in dotasks loop. On input debounce the delay could be shortcuted and a fault condition could be triggered without being real.
> cnc delay will be executed without early exit

- CHANGELOG.md
- uCNC/src/core/interpolator.c
- uCNC/src/core/motion_control.c
- uCNC/src/core/parser.c
- uCNC/src/core/planner.c
- uCNC/src/hal/boards/avr/boardmap_mks_dlc.h
- uCNC/src/hal/boards/avr/boardmap_rambo14.h
- uCNC/src/hal/boards/avr/boardmap_ramps14.h
- uCNC/src/hal/boards/avr/boardmap_uno.h
- uCNC/src/hal/mcus/avr/mcu_avr.c
- uCNC/src/hal/mcus/avr/mcumap_avr.h
-added missing globals to init functions with FORCE_GLOBALS_TO_0 enabled
-renamed PWM OCR to PWM CHANNEL and all boardmaps for AVR
-fixed PWM config macro (was unstable on Mega boards)
-fixed UBRR calculation for AVR
> several fixes that affected Arduino Mega

- CHANGELOG.md
- makefiles/avr/makefile
- uCNC/src/cnc.c
- uCNC/src/cnc_config_helper.h
- uCNC/src/core/interpolator.c
- uCNC/src/core/io_control.c
- uCNC/src/core/motion_control.c
- uCNC/src/core/parser.c
- uCNC/src/core/planner.c
- uCNC/src/core/planner.h
- uCNC/src/hal/mcus/avr/mcu_avr.c
- uCNC/src/hal/mcus/avr/mcumap_avr.h
- uCNC/src/hal/mcus/samd21/mcumap_samd21.h
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f1x/mcumap_stm32f1x.h
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- uCNC/src/hal/mcus/stm32f4x/mcumap_stm32f4x.h
- uCNC/src/hal/tools/tool.c
- uCNC/src/hal/tools/tool_helper.h
- uCNC/src/interface/protocol.c
- uCNC/src/interface/protocol.h
- uCNC/src/interface/serial.c
- uCNC/src/interface/serial.h
- uCNC/src/interface/settings.c
- uCNC/src/module.h
- uCNC/src/utils.h
- fixed set PWM macro for AVR (cause issues on Mega boards)
- fixed several C99/GNU99 compliance warnings
- fixed dir mask implementation ($2)
- fixed settings crc calculation (without lookup table)
- fixed output pin toggle macro for AVR
- fixed AVR RX pin setup
- fixed BYTE_OPS redefinition
> Fix warnings

- .gitignore
- CHANGELOG.md
- uCNC/cnc_config.h
- uCNC/src/core/interpolator.c
- uCNC/src/hal/mcus/virtual/mcu_virtual.c
fixed laser not turning on with laser mode enabled and after new feed motion command is issued without S word update and M3 active
> laser not turning on with M3 and S word missing

- CHANGELOG.md
- uCNC/cnc_config.h
- uCNC/src/core/parser.c
added option to accept G0 and G1 without explicit axis words to target
> optional G0-G1 without axis

- CHANGELOG.md
- uCNC/src/core/parser.c
- fixed error were coordinates would be forgotten/override if applying multiple G10 commands for different axis (ex. G10L20X0 and G10L20Y0)
> coordinates override on multiple G10

- CHANGELOG.md
- uCNC/src/cnc.c
- uCNC/src/core/io_control.c
- uCNC/src/core/io_control.h
- uCNC/src/core/motion_control.c
- fixed logic error when both limits switches are active for an axis (not dual-drive) and are inverted, trigger would only happen if both were pressed
> logic error with dual limit switch inverted

- CHANGELOG.md
- uCNC/src/core/io_control.c
- filter limit switch triggering when homing (dual axis) that was being incorrectly mixed after #205
> XOR limits while HOMING

- CHANGELOG.md
- uCNC/cnc_hal_config.h
- uCNC/src/cnc.c
- uCNC/src/cnc_hal_config_helper.h
- uCNC/src/core/io_control.c
- uCNC/src/hal/boards/avr/boardmap_ramps14.h
- uCNC/src/hal/tools/tools/spindle_besc.c
- uCNC/src/module.c
- uCNC/src/modules/encoder.c
- encoder can now be enabled without module dependencies
- moved additional encoder callbacks to module (via listeners)
- added RPM example in BESC spindle
- fixed module send_pins_states default handler
> modifications to encoder module

- CHANGELOG.md
- uCNC/src/cnc.c
- moved cnc_dotasks hook to allow this hook to be called even with an active hold state
> moved cnc_dotasks hook

- uCNC/src/core/parser.c
- uCNC/src/core/parser.h
- Q word recognized even if canned cycles not enabled
- added macro for extended codes uniformization
> parser tweak for modules

- CHANGELOG.md
- uCNC/src/modules/tmc.c
- uCNC/src/modules/tmc.h
- uCNC/src/modules/tmcdriver.c
- fixed M914 initialization
- added shadow registers of write only registers of TMC
- changed TMC settings stored in RAM to prevent softreset defaults loading
- added M913 command (stealthchop)
> TMC driver redesign

- CHANGELOG.md
- uCNC/src/cnc.c
- uCNC/src/core/interpolator.c
- uCNC/src/core/motion_control.c
- uCNC/src/core/motion_control.h
- uCNC/src/core/parser.c
- uCNC/src/core/parser.h
- uCNC/src/core/planner.c
- uCNC/src/core/planner.h
- uCNC/src/hal/tools/tools/laser.c
- modified tool speed/direction calculation to correctly set the minimal output speed or do a full stop. An example of this is the minimal ouput of a PWM controlled laser tool that sets a minimal PWM ouput to make laser response faster from 0 to desired value.
> Tool correct minimal speed

- CHANGELOG.md
- README.md
- uCNC/src/hal/mcus/avr/mcumap_avr.h
- uCNC/src/hal/mcus/esp32/mcu_esp32.c
- uCNC/src/hal/mcus/esp8266/mcu_esp8266.c
- uCNC/src/hal/mcus/lpc176x/mcu_lpc176x.c
- uCNC/src/hal/mcus/mcu.h
- uCNC/src/hal/mcus/samd21/mcu_samd21.c
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/virtual/mcu_virtual.c
- better µs delay for all platforms (now accepts 16bit value as argument) and better precision for AVR
> Better µs delay

- uCNC/src/hal/boards/stm32/stm32.ini
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f1x/mcumap_stm32f1x.h
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- uCNC/src/hal/mcus/stm32f4x/mcumap_stm32f4x.h
- SMT32 Peripheral clocks now calculated from APB (slow or fast) settings and F_CPU
> STM32 peripheral clocks now calculated from APB settings

- uCNC/src/modules/softspi.c
- uCNC/src/modules/softuart.c
- removed atomic from soft uart and spi functions. With slow speed communications the long atomic operation caused UART and USB ISR to miss character reception.
> removed atomic from soft uart and spi functions

- uCNC/cnc_config.h
- uCNC/src/cnc.c
- uCNC/src/core/io_control.c
- uCNC/src/core/io_control.h
- added option to debug IO alarm fault verbose. This will print the limits and controls states that triggered the alarm/fault condition to allow debug of faulty wiring and noise
> added option to debug IO alarm fault

- uCNC/src/cnc.c
- uCNC/src/cnc.h
- uCNC/src/cnc_hal_config_helper.h
- uCNC/src/core/interpolator.c
- uCNC/src/core/io_control.c
- uCNC/src/core/motion_control.c
- uCNC/src/core/parser.c
- uCNC/src/core/parser.h
- uCNC/src/hal/mcus/virtual/mcu_virtual.c
- uCNC/src/interface/grbl_interface.h
- uCNC/src/interface/protocol.c
Redesigned internal machine states:
- fixed multi drive axis compilation error
- added limit alarm with no motion (no reset required)
- replaced halt state by not homed
- added limits exec state
- high priority (lower values) alarms now require user reset (hard or soft reset)
- prevent reset loop while emergency stop is pressed
> 352 bug some alarms are not being printed

- uCNC/cnc_config.h
- uCNC/src/hal/boards/rp2040/rp2040.ini
- uCNC/src/hal/mcus/rp2040/mcu_rp2040.c
- uCNC/src/hal/mcus/rp2040/rp2040_arduino.cpp
- fixed compilation error on EEPROM emulation for RP2040
- update PIO ini for RP2040 to use the latest framework version
- removed global RAM_ONLY_SETTINGS
> fixed RAM_ONLY_SETTINGS by default

- uCNC/src/cnc.c
- prevent RT command for report to be cleared on RT commands exec
- report send is now only cleared after sending the report
- don't block ? command even with auto report enabled
> prevent ? report command clear without response

- uCNC/src/modules/digimstep.c
- uCNC/src/modules/digipot.c
- uCNC/src/modules/tmcdriver.c
- replaced missing pin checking by ASSERT_PIN macro (TMC_SPI_CS pins and RAMBO digital msteps)
- added warnings and errors for loaded modules that don't have the extension events enabled
> replaced missing pin checking by ASSERT_PIN macro

- uCNC/src/modules/system_menu.c
- uCNC/src/modules/system_menu.h
- dynamic menu macro calls menu append directly
- render header for static menu item rom string is copied to ram on system menu module
> System menu fixes

- uCNC/src/cnc.c
- fixed jog motion cancelation that causes machine to loose position synchronization between systems
> fixed jog cancelation position synch

- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
Implemented error recovery for I2C on STM32 microcontrollers
These couple of if statements improve the time it takes to respond to errors like negative acknowledge and bus lines getting stuck low. After a bit of testing it seems to prevent the I2C peripheral from getting stuck in an invalid state.
> Improved error recovery for STM32 microcontrollers

- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- modified ISR to prevent I2C response fail. NACK is sent by the slave sending a stop condition
- stop ISR flag is not signal on repeated start causing the response callback to never get called. added additional callback condition on ISR
> modified ISR to prevent I2C response fail

- uCNC/src/core/interpolator.c
- prevent JOG synch problem on cancel (with soft limits enabled)
> prevent JOG synch problem on cancel

- uCNC/src/cnc.c
- uCNC/src/interface/protocol.c
- uCNC/src/interface/serial.c
- uCNC/src/interface/serial.h
- new serial tx busy function use to evaluate status report print skip and prevent protocol message contamination (interleaved messages)
- code cleaning
> new serial tx busy function

- uCNC/src/cnc.c
- Force parser re-sync on gcode error to prevent sync error between motion control and parser
> Force parser re-sync on gcode error

- uCNC/cnc_config.h
- uCNC/src/cnc_hal_config_helper.h
- uCNC/src/core/interpolator.c
- uCNC/src/hal/tools/tools/laser_ppi.c
- uCNC/src/interface/protocol.c
- uCNC/src/interface/settings.c
- uCNC/src/interface/settings.h
option to use any linear or s-curve profile via setting $14
> Configurable s-curve

- uCNC/src/cnc.c
- uCNC/src/core/interpolator.c
- fix JOG sticky state on cmd error
- moved state flags clearing from interpolator to the main loop
> fix JOG sticky state on cmd error

- uCNC/src/cnc_build.h
- uCNC/src/hal/mcus/lpc176x/lpc176x_arduino.cpp
- uCNC/src/hal/mcus/lpc176x/mcu_lpc176x.c
- uCNC/src/hal/mcus/samd21/mcu_samd21.c
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
Prevent usb flush infinite loop if unconnected allowing other ports like UART to flush the message protocol.
These changes affect mainly STM32 and SAMD21 since other boards with USB are using Arduino CDC.
> Prevent usb flush infinite loop if unconnected

- uCNC/cnc_hal_config.h
- uCNC/src/cnc.c
- uCNC/src/hal/boards/avr/avr.ini
- uCNC/src/hal/kinematics/kinematic_scara.c
- modified cnc delay to run dotasks instead of only io_dotasks
- prevent re-entrant code inside dotasks events
- redesign the main loop tasks to prevent re-entrant code on the event callbacks
- force interlocking check before getting the alarm to force alarm code refresh if alarm condition is triggered by ISR
- fixed scara kinematics code to match new multi axis
> Dotasks code redesign

- uCNC/src/cnc.c
- fixes sticky RUN state after alarm and CNC stop. This would prevent the reset to continue loop to continue and enter the reset loop
> fixed RUN state clear after alarm while running

- uCNC/src/cnc.c
- allow part of realtime commands even during reset
- moved report logic to realtime commands
- prevent alarm overriding unless the alarm has a higher precedence (lower value)
> modified alarm logic

- uCNC/src/core/io_control.c
- prevent alarm on enabling $21 for the first time by allowing the limits states to be updated even if $21 is disabled
> prevent alarm on enabling $21 for the first time

- uCNC/src/cnc.c
- uCNC/src/core/parser.c
- uCNC/src/hal/mcus/esp32/esp32_arduino.cpp
- uCNC/src/hal/mcus/esp8266/esp8266_arduino.cpp
- uCNC/src/hal/mcus/rp2040/rp2040_arduino.cpp
- uCNC/src/interface/serial.c
- uCNC/src/interface/serial.h
- uCNC/src/interface/settings.c
- uCNC/src/interface/settings.h
- settings crc takes data size in account
- modified function call flow to reduce code size in AVR UNO
- modified settings to allow data size from 8bit to 16bit (prevent clipping saved data)
> settings crc takes data size in account

- uCNC/src/core/interpolator.c
- Fix random stalls at the end of a deacceleration motion to a full stop. Under particular condition and due to float rounding errors speed may reach negative values and the motion being unable to continue.
> Fix random stalls

- uCNC/src/hal/mcus/esp32/mcumap_esp32.h
- uCNC/src/hal/mcus/esp8266/mcumap_esp8266.h
- uCNC/src/modules/softi2c.h
- uCNC/src/modules/softspi.h
- custom short delays for ESP MCU (using internal cycle count)
- correct soft spi frequency clamp
> ESP software delays for emulated protocols

- uCNC/src/hal/mcus/esp32/mcu_esp32.c
- uCNC/src/hal/mcus/esp32/mcumap_esp32.h
Modified ESP32 software PWM emulation to improve stepper stepping resolution at higher step rates:
With software PWM:
- steppers use dedicated timer
- servo timer used as both servo and PWM timer running at 128KHz
> Esp32 better softpwm

- uCNC/src/hal/mcus/stm32f4x/mcumap_stm32f4x.h
The PWM configuration code had hard-coded usage of the `PWM0_ENREG` and `PWM0_APBEN`, it now uses the `__indirect__` macro to select the correct registers depending on the specified PWM pin.
> Fixed PWM configuration macro for STM32 F4x family MCUs

- uCNC/src/cnc.c
- uCNC/src/cnc.h
- uCNC/src/core/interpolator.c
- uCNC/src/core/motion_control.c
- uCNC/src/hal/kinematics/kinematic_cartesian.c
- uCNC/src/hal/kinematics/kinematic_corexy.c
- uCNC/src/hal/kinematics/kinematic_delta.c
- uCNC/src/hal/kinematics/kinematic_linear_delta.c
- uCNC/src/hal/kinematics/kinematic_scara.c
- exec states cleaning
- homing flag state is set and cleared inside the homing cnc call
- run flag is cleared and set only at the ITP level
> CNC state flags cleaning

- uCNC/src/core/planner.c
- uCNC/src/hal/tools/README.md
- uCNC/src/hal/tools/tool.c
- uCNC/src/hal/tools/tool.h
- uCNC/src/hal/tools/tools/laser_pwm.c
- uCNC/src/hal/tools/tools/pen_servo.c
- uCNC/src/hal/tools/tools/spindle_besc.c
- uCNC/src/hal/tools/tools/spindle_pwm.c
- uCNC/src/hal/tools/tools/vfd_pwm.c
- fixed tool speed report functions to report always in GCode S units
- modified tool speed range function to allow inverse convertion
> fixed tool speed report functions

- uCNC/src/core/motion_control.c
- uCNC/src/core/motion_control.h
- Added new motion control incremental jog command. This can be directly accessed by other systems to make an incremental jog without having to go though the parser.
> added motion control incremental jog command

- uCNC/src/hal/boards/avr/avr.ini
- uCNC/src/hal/mcus/avr/mcumap_avr.h
- fix UART ISR vector macro for AVR (single and multiple UART capable MCU's)
- added configuration for Atmega328PB variants
> fix UART ISR vector macro for AVR

- uCNC/src/hal/tools/tools/spindle_pwm.c
- uCNC/src/hal/tools/tools/vfd_pwm.c
- uCNC/src/modules/pid.c
- uCNC/src/modules/pid.h
- Changed `HZ_TO_MS` macro to calculate the period of the given frequency in milliseconds
- Added a check to PID update period to make sure we are not dividing by zero.
> Corrected PID implementation.

- uCNC/src/hal/boards/esp32/esp32.ini
- uCNC/src/hal/mcus/esp32/mcumap_esp32.h
- make EEPROM arduino library the default for ESP32
> make EEPROM arduino library the default for ESP32

- uCNC/src/cnc.c
- prevent spindle restore message at restart. This bug was introduced by #631
> prevent spindle restore message at restart

- uCNC/src/interface/settings.c
- uCNC/src/interface/settings.h
- fixed settings reset propagation
- string settings now can use the same char buffer
- string settings will work like workspaces (save on change)
> fixed settings reset propagation

- uCNC/src/cnc.c
- uCNC/src/core/motion_control.c
- uCNC/src/core/planner.c
- uCNC/src/core/planner.h
- moved spindle restore to planner override
- filters the message showing if an override was made during a hold condition only
- prevent probe to clear tool status
> moved spindle restore to planner override

- uCNC/src/hal/mcus/esp32/mcu_esp32.c
in mcu_esp32.c there are a couple of build failures related to servo
* duplicated variables
* conflicting function forward-declaration vs definition
which are likely mistakes from a previous merge.
> Removed duplicated servo variables for ESP32

- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f1x/mcumap_stm32f1x.h
- allow use of standard speed mode for I2C
- remove deprecated code
> Allow I2C low speed clocks

- uCNC/src/hal/mcus/esp8266/mcu_esp8266.c
- fix wifi initialization on ESP8266 (was starting before EEPROM initialization)
> fix wifi initialization on ESP8266

- uCNC/src/interface/serial.c
There is a bug in serial_available() that will make the system ignore any incoming bytes from default_stream. With UART as default_stream, the system will stop talking to a sender software on a host machine.
To repro:
1. enable DEBUG_STREAM (mapped to default_stream)
2. register multiple serial streams
3. build and flash
4. connect system to a sender via UART, and verify the two can communicate
5. send data via any stream that is not default_stream (i.e. not UART)
6. sender can no longer communicate with the system
This diff fixes the bug by skipping DEBUG_STREAM only when it is not default_stream.
TBH I am not sure why we want to skip DEBUG_STREAM in serial_available().
serial_available() checks number of bytes in the RX buffer.
In almost all scenarios DEBUG_STREAM is used to send debug …
> Only skip DEBUG_STREAM when it is not default_stream

- uCNC/src/interface/serial.c
- Prevent using debug stream before initialization causing a crash
> Prevent using debug stream before initialization

- makefiles/virtual/mcu_virtual.cpp
- uCNC/src/core/interpolator.c
- uCNC/src/core/planner.c
- prevent floating point round errors in speed calculations when time slices a too small
> prevent floating point round errors in speed

- uCNC/cnc_config.h
- uCNC/src/cnc.c
- uCNC/src/cnc_hal_config_helper.h
- uCNC/src/core/interpolator.c
- uCNC/src/core/interpolator.h
- uCNC/src/hal/boards/avr/avr.ini
Experimental ITP loop running inside an ISR/task.
This has the advantage of preventing the step generation starving when running very long and intensive calculations tasks and run independent from the main loop.
> Interpolator loop feed as a task

- uCNC/src/core/motion_control.c
There seems to be a mistake in the alarm triggered after homing axis pull off fails, instead of firing `EXEC_ALARM_HOMING_FAIL_PULLOFF`, `EXEC_ALARM_HOMING_FAIL_APPROACH` gets sent and confusion ensues. This small pull request addresses this issue. After a quick check, the definition of `EXEC_ALARM_HOMING_FAIL_PULLOFF` didn't seem to be used anywhere in the project which is why I believe this is a simple typo.
> Change homing alarm failure type

- uCNC/src/hal/boards/stm32/boardmap_blackpill.h
- uCNC/src/hal/mcus/avr/mcumap_avr.h
- uCNC/src/hal/mcus/stm32f1x/mcumap_stm32f1x.h
- uCNC/src/hal/mcus/stm32f4x/mcumap_stm32f4x.h
Fix STM32 compilation error if probe not defined. This caused mcu_enable_probe_isr and mcu_disable_probe_isr not to be defined.
> Fix STM32 compilation error if probe not defined

- uCNC/src/hal/mcus/stm32f0x/mcu_stm32f0x.c
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
Fixed some minor issues with the SPI implementation in STM32 family microcontrollers.
- Missing 'bitwise not' operator before clearing bits in control register 1
- Polling SPI1 in xmit instead of the configured SPI_REG
> Fix SPI implementation for STM32 MCUs

- uCNC/src/hal/mcus/stm32f0x/mcu_stm32f0x.c
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
This fixes some minor issues I found.
- Assign spi_dma_enable to configuration value.
- Fix interrupt driven spi transfers. The code was causing issues at higher SPI clock speeds.
> Minor STM32 fixes

- uCNC/src/hal/boards/boarddefs.h
- uCNC/src/hal/boards/pin_mapping_helper.h
New pin mapping helper that allow an easier pin mapping definition/setup for boardmaps.
To define a pin on a board you needed to define the bit and port of the pin like this
```
#define STEP0_BIT 2	 // assigns STEP0 pin
#define STEP0_PORT D // assigns STEP0 port
```
This now can also be done like this
`#define STEP0_PIN D2	 // assigns STEP0 pin`
On MCU's like the ESP32 and the RP2040 this can be done like this
`#define STEP0_PIN GPIO3	 // assigns STEP0 pin`
The new pin mapping helper will generate under the hood the BIT and PORT definitions.
To prevent configuration errors, if the pin was already defined via BIT and PORT, that will take precedence over the new PIN definition and the PIN definition will have no effect.
> New pin mapping helper

- uCNC/src/hal/boards/stm32/stm32.ini
- uCNC/src/module.h
- locked STM32 platform version to prevent compilation issues from breaking changes in the platform/framework
- updated flash offset setting on boards with bootloader
> Locked STM32 platform version

- uCNC/src/modules/system_menu.c
- uCNC/src/modules/system_menu.h
This PR makes the system_menu_goto a global function. It also makes the function set action timeout and redraw flags to make sure the new screen gets shown even if it's not called from system_menu_action.
> Make system_menu_goto global

- uCNC/src/hal/tools/tools/README.md
- uCNC/src/hal/tools/tools/pen_servo.c
This fixes the range function for the pen servo tool:
- Remove the unused `PEN_SERVO_MID` option
- Allow to have `PEN_SERVO_LOW` be greater than `PEN_SERVO_HIGH`
- Fix an type conversion overflow in the range converter
- Add safety clamping before sending values to PWN
> Pen Servo Tool fixes

- uCNC/src/hal/boards/rp2040/rp2040.ini
- Lock RP2040 framework version to fix compilation error
> Lock RP2040 framework version

- uCNC/src/modules/system_menu.c
- uCNC/src/modules/system_menu.h
This PR makes the `jog_distance` and `jog_feed` globally accessible. My use case for this is to allow hardware buttons to use the same jogging parameters as set in the menu. Please let me know if this is fine or if these should stay static.
> Make jog parameter variables global

- uCNC/src/hal/boards/esp32/boardmap_mks_dlc32.h
- uCNC/src/hal/boards/esp32/boardmap_mks_tinybee.h
- uCNC/src/hal/mcus/esp32/mcu_esp32.c
- independent step/dir and pwm/servo signal generation via I2S/realtime
- fixed I2S loop to prevent crash with option USE_I2S_REALTIME_MODE_ONLY
- cleaned oneshot timer code
- fixed SPI configuration crash errors
> I2S and realtime IO fixes

- uCNC/src/cnc.c
- fix status report send when sender adds LF after ?. This seems to cause issues in UGS
- Arduino Mega board also seems to respond better with this change
> fix status report send when sender adds LF after ?

- uCNC/src/interface/serial.c
- uCNC/src/interface/serial.h
- fix compilation error with custom debug stream
- added debug stream customization example
> fix error with custom debug stream

- uCNC/src/hal/kinematics/kinematic_corexy.c
- uCNC/src/hal/kinematics/kinematic_corexy.h
- uCNC/src/hal/kinematics/kinematicdefs.h
- uCNC/src/hal/kinematics/kinematics.h
CoreYZ would be redundant because normally X and Y are interchangeable
> add CoreXZ kinematic

- uCNC/src/hal/boards/avr/avr.ini
- uCNC/src/hal/boards/esp32/esp32.ini
- uCNC/src/hal/boards/lpc176x/lpc176x.ini
- uCNC/src/hal/boards/rp2040/rp2040.ini
- uCNC/src/hal/boards/samd21/samd21.ini
- uCNC/src/hal/boards/stm32/stm32.ini
- uCNC/src/hal/mcus/mcus.h
- Preset the MCU when building to a custom MCU to prevent the default boardmap include in the code resulting in compilation errors
> fixed custom MCU build flags

- uCNC/src/core/parser_expr.c
- fix parser backtracking char cleaning
- this caused an error if the value of the last parameter on a line was negative for example (G1F500X-10)
> fix parser backtracking char cleaning

- uCNC/src/interface/grbl_protocol.c
- uCNC/src/interface/grbl_stream.c
- uCNC/src/utils.h
- fix debug stream overflow reset not reseting properlly (credits to [ricochet1k](https://github.com/ricochet1k))
- fix timeout macro when free_micros turns around (credits to [ricochet1k](https://github.com/ricochet1k))
- modified timeout to uint32_t. Setting a timeout of -1 will take 71 minutes to occur
> Fix debug stream

- uCNC/src/utils.h
- fix timeout macro typo in converting from ms to us
- reverted timeout_us macro to prevent compiler optimizations that would lead to out of order execution
> fix timeout macro

- uCNC/src/interface/grbl_stream.c
- removed guard preventing debug stream usage unless it was the default stream. This allows to continue using the debug stream without restrictions
> removed guard preventing debug stream usage

- uCNC/cnc_config.h
- uCNC/src/core/parser.c
- added option to prevent machine lock after program end (M2 or M30)
> added option to prevent machine lock after program end

- uCNC/src/cnc.c
- uCNC/src/core/parser.c
- uCNC/src/core/parser.h
- redesigned M2/M30 to match LinuxCNC reseting the parser parameters
- default mode with program locking
- option mode without lock (similar to Grbl)
> redesigned M2/M30 to match LinuxCNC

- uCNC/src/interface/grbl_protocol.c
issue was introduced in 0caa36f4; without this, the behaviour is the opposite of GRBL
> fix inversion of status_report_mask position type bit

- uCNC/src/core/parser.c
- uCNC/src/interface/grbl_settings.h
- fixed G10 offset when G91 is active and ignoring G92 coordinates
- fixed G92 calculations relative to current coordinate system
- making non modal commands sync (except G53) to prevent coordinate WCO to be applied ahead of time
> fixed G10 and G92 offsets

- uCNC/src/core/parser.c
- better parser validation function
- motion commands are now validaded with or without explicit motion command words in the block
- fixed motion mantissa parser ghost value that leaded to incorrect modal states report
> Improved parser validation and modal states report fix

- uCNC/src/core/parser.c
issue was introduced in fc0d9d31
without this, the ["perform motion" check](https://github.com/tomjnixon/uCNC/blob/74dda7286e2f7b189394fadee4711bdf473c6317/uCNC/src/core/parser.c#L1782) ignores the command
i'm not sure if this is the right approach, but it works and seems to make sense
> fix ignored G53

- uCNC/src/modules/ic74hc595.h
fix bug on ic74hc595_get_pin macro by removing the bit shift since the BITMASK already done that operation
> fix bug on ic74hc595_get_pin macro

- uCNC/src/cnc.c
- uCNC/src/cnc.h
- uCNC/src/core/motion_control.c
- uCNC/src/core/parser.c
- uCNC/src/hal/kinematics/kinematic_cartesian.c
- uCNC/src/hal/kinematics/kinematic_corexy.c
- uCNC/src/hal/kinematics/kinematic_delta.c
- uCNC/src/hal/kinematics/kinematic_linear_delta.c
- uCNC/src/hal/kinematics/kinematic_scara.c
- uCNC/src/interface/grbl_settings.c
- uCNC/src/modules/system_menu.c
- modified axis homing to report error if $21 disabled
- fixed system menu complation errors in several kinematics (DELTAs and SCARA)
- prevent machine unlocking on homing with error code
> axis homing error if $21 disabled

- uCNC/src/core/parser.c
- fix validation error of custom commands with axis words
> fix error of custom commands with axis words

- uCNC/src/hal/boards/stm32/stm32.ini
- uCNC/src/hal/mcus/stm32f0x/mcu_stm32f0x.c
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- added eeprom emulation option on STM32 to separate from RAM_ONLY_SETTINGS
- fixed sector sizes depending on flash size for STM32F4
> Added EEPROM emulation option on STM32

- uCNC/src/interface/grbl_protocol.c
prevents garbage data (random positions) printing if the axis count is smaller then 3.
> fix status position print if axis < 3

- uCNC/src/hal/kinematics/kinematic_cartesian.c
- uCNC/src/hal/kinematics/kinematic_corexy.c
- uCNC/src/hal/kinematics/kinematic_delta.c
- uCNC/src/hal/kinematics/kinematic_linear_delta.c
- uCNC/src/hal/kinematics/kinematic_rtheta.c
- uCNC/src/hal/kinematics/kinematic_scara.c
- allow softlimits to be ignored if $13x distance is 0 (this may not be the applied in all axis). Some kinematics still require some of the settings to be a non 0 value to work properlly
> allow softlimits to be ignored if $13x distance is 0
