- uCNC/mcu.h
- uCNC/mcus/avr/README.md
- uCNC/mcus/avr/mcu_avr.c
- uCNC/mcus/avr/mcumap_mega_rambo14.h
- uCNC/mcus/avr/mcumap_uno_grbl.h
New generic PWM implementation for atmega MCU.
Fixed induced bug on mcu.h created on the last patch.
> Better AVR support

- uCNC/config.h
- uCNC/grbl_interface.h
- uCNC/mcus/avr/makefile
- uCNC/mcus/avr/mcu_avr.c
- uCNC/mcus/avr/mcumap_mega_rambo14.h
-new versioning
-fixed makefile
-fixed mcumap for mega rambo
-fixed mcu_avr eeprom access for atmega2560
> New versioning

- uCNC/mcus/virtual/uCNC.dev
- uCNC/parser.c
-fixes bug that doen't convert feed to mm/s if feed not explicitly declared
-small modification in cppdev project settings to fix compilation error
> bug fix in setting feed in inch mode and cppdev project file

- uCNC/parser.c
-fixed parsing of reset command that accepted invalid command formats
> Invalid reset command formats accepted

- uCNC/config.h
- uCNC/interpolator.c
- uCNC/mcus/virtual/uCNC.dev
Implemented Dynamic Step Spread Algorithm
- similar to AMASS for Grbl but with a few changes
- has less impact on ISR than AMASS (only activated when needed) at the cost of a single ```if```
> Dynamic step spread algorithm

- uCNC/cnc.c
- uCNC/config.h
- uCNC/io_control.c
- uCNC/io_control.h
- uCNC/parser.c
- uCNC/parser.h
- uCNC/protocol.c
- fixed modalstates report
- fixed active tools report
- fixed coolant commands (M7, M8 and M9)
> fix modal states and coolant

- uCNC/cnc.c
- uCNC/mcu.h
- uCNC/mcus/avr/boardmap_grbl.h
- uCNC/mcus/avr/mcu_avr.c
- uCNC/mcus/avr/mcumap_avr.h
- uCNC/mcus/stm32f10x/mcu_stm32f10x.c
- uCNC/mcus/stm32f10x/mcumap_stm32f10x.h
- disabling probing ISR at startup to avoid unintended firing
> fix probing ISR

- uCNC/config.h
- uCNC/interpolator.c
- uCNC/mcus/avr/mcumap_avr.h
- uCNC/mcus/stm32f10x/mcumap_stm32f10x.h
- uCNC/motion_control.c
- uCNC/parser.c
- uCNC/planner.c
- uCNC/utils.h
- improved fast math functions and some bug fixes
- new pow2 fast math function
- some changes to core code to make use of new pow2
> improved fast math function

- uCNC/mcudefs.h
- uCNC/mcus/stm32f10x/mcu_stm32f10x.c
-bug fix TX pin configuration for hardware serial
-forces sync TX (async isn't working very well)
> Fixed hardware serial code for STM32F1

- uCNC/mcu.h
- uCNC/mcus/avr/boardmap_grbl.h
- uCNC/mcus/avr/boardmap_rambo14.h
- uCNC/mcus/avr/boardmap_ramps14.h
- uCNC/mcus/avr/mcu_avr.c
- uCNC/mcus/avr/mcumap_avr.h
- uCNC/mcus/stm32f10x/boardmap_bluepill.h
- uCNC/mcus/stm32f10x/mcu_stm32f10x.c
- uCNC/mcus/stm32f10x/mcumap_stm32f10x.h
- uCNC/mcus/stm32f10x/startup_stm32f103xb.s
-Implementation of an RTC to power future modules and features to integrate in µCNC
> Internal rtc

- src/cnc.h
- src/cnc_config.h
- src/cnc_config_helper.h
- src/hal/boards/stm32/boardmap_bluepill.h
-added option to disable controls or limits IO globally
> added option to disable controls or limits IO globally

- src/cnc.c
- src/interface/grbl_interface.h
- src/interface/protocol.c
- src/interface/serial.c
-improved real time status report no (no longer needing and empty buffer to send report-more responsive)
-response protocol collisions avoidance
-axis configuration
> improved real time status report

- src/core/interpolator.c
- src/core/motion_control.c
- src/core/motion_control.h
- src/core/planner.c
- src/core/planner.h
-minor modifications to planner buffer to keep buffer control more simple
-main stepper information transition from motion control to interpolator fixed and normalized naming
-modified path for non motion and motion blocks to allow internal function to be inlined
> Planner optimizations

- src/cnc_config.h
- src/core/parser.c
-added option to ignore gcode with undefined axis
> option to ignore gcode with undefined axis

- src/cnc.c
- src/cnc.h
- src/core/parser.c
- src/interface/serial.c
-improve startup code with reduced code size and stable results
-fixed startup blocks result not printing in the same line
-moved reset to continue message to the end of the alarm condition
-added command discard call to prevent infinite error loop
-minor fix in exec state flag clear
> Startup code improvement

- src/cnc.c
-run tasks on startup block call to prevent overflowing buffers. This also aborts unlocking on block error
> Startup blocks exec on call

- CHANGELOG.md
- src/cnc.c
- src/cnc_config.h
-added extra delay for coolant on resume from any hold (hold, safety-door) to emulate Grbl
> added extra delay for coolant on resume from hold

- src/cnc.c
-fix coolant function call (deprecated code)
> fix coolant function call

- CHANGELOG.md
- uCNC/src/hal/boards/samd21/boardmap_mzero.h
- uCNC/src/hal/mcus/samd21/mcu_samd21.c
- uCNC/src/hal/mcus/samd21/mcumap_samd21.h
-implemented SAMD21 analog read
> implemented SAMD21 analog read

- CHANGELOG.md
- makefiles/stm32f103/Makefile
- uCNC/src/core/io_control.c
- uCNC/src/core/io_control.h
- uCNC/src/hal/boards/stm32/boardmap_bluepill.h
- uCNC/src/hal/mcus/stm32f10x/mcu_stm32f10x.c
- uCNC/src/hal/mcus/stm32f10x/mcumap_stm32f10x.h
-implemented analog input reading on STM32
-implemented io_control function to read analog pins
> implemented analog input reading on STM32

- CHANGELOG.md
- uCNC/cnc_config.h
- uCNC/src/core/io_control.c
- uCNC/src/core/io_control.h
- uCNC/src/hal/boards/samd21/boardmap_mzero.h
- uCNC/src/hal/mcus/samd21/mcu_samd21.c
- uCNC/src/hal/mcus/samd21/mcumap_samd21.h
-implemented SAMD21 input on change ISR
> implemented SAMD21 input on change ISR

- CHANGELOG.md
- uCNC/cnc_hal_config.h
- uCNC/src/cnc.c
- uCNC/src/hal/tools/tool.c
-added the tool PID to the cnc scheduler
> added the tool PID to the cnc scheduler

- CHANGELOG.md
- uCNC/src/core/interpolator.c
- uCNC/src/core/io_control.c
- uCNC/src/hal/kinematics/kinematicdefs.h
- uCNC/src/hal/mcus/avr/mcumap_avr.h
- uCNC/src/hal/mcus/samd21/mcumap_samd21.h
- uCNC/src/hal/mcus/stm32f10x/mcumap_stm32f10x.h
- uCNC/src/modules/encoder.c
- uCNC/src/modules/encoder.h
-interpolator step generation for modified no-stepper actuators
> modified no-stepper actuators

- CHANGELOG.md
- makefiles/virtual/main.c
- makefiles/virtual/uCNC.dev
- makefiles/virtual/virtualserial.c
- uCNC/src/core/interpolator.c
- uCNC/src/core/utils.h
-minor modification to bresenham variables initialization.
> minor modification to bresenham variables initialization

- CHANGELOG.md
- uCNC/src/core/planner.c
-fixed spindle override max min values set in config.h
> fixed spindle override max min values

- CHANGELOG.md
- uCNC/cnc_hal_config.h
- uCNC/src/interface/protocol.c
- uCNC/src/interface/settings.c
-modified settings code (smaller code)
-fixes PID controller setting address (out of range)
> modified settings code

- CHANGELOG.md
- uCNC/src/core/interpolator.c
- uCNC/src/core/planner.c
- fixed overrides bug due to commented code that disable negative accelerations when slowing motion. Also done slight step ISR modifications to DSS calculations.
> fix speed overrides bug when slowing down

- CHANGELOG.md
- uCNC/cnc_config.h
- uCNC/src/cnc_config_helper.h
- uCNC/src/core/interpolator.c
- modified DSS to force step ISR frequency to update on DSS change
- removed DSS minimum step limitation to prevent DSS algorithm on/off oscillation resulting in a smoother motion
- added configurable DSS cutoff frequency
> linear accel and deaccel smoother motion

- CHANGELOG.md
- uCNC/src/core/interpolator.c
modified interpolator to update the the tool inside the ISR call (not only when speed changed). The ISR was modified to carry segment information to the next generated step without before segment evaluation
> fixed laser update flaw

- CHANGELOG.md
- uCNC/cnc_config.h
- uCNC/src/cnc.c
- uCNC/src/core/interpolator.c
- uCNC/src/core/interpolator.h
- uCNC/src/core/motion_control.h
- uCNC/src/core/parser.c
- uCNC/src/core/parser.h
- uCNC/src/core/planner.c
- uCNC/src/core/planner.h
- uCNC/src/hal/tools/tool.c
- uCNC/src/interface/protocol.c
-removed deprecated option USE_SPINDLE and USE_COOLANT
-fixed initialization code with FORCE_GLOBALS_TO_0
> removed deprecated option USE_SPINDLE and USE_COOLANT

- CHANGELOG.md
- uCNC/src/core/interpolator.c
- uCNC/src/core/planner.c
- uCNC/src/hal/mcus/avr/mcumap_avr.h
-fixed bug on multi-segmented motion control line where planner was changing the feed rate speed of the motion block (bug affected 16bit bresenham)
-fixed compilation error with DSS disabled
> fixed 16bit bresenham mode

- CHANGELOG.md
- uCNC/src/cnc.c
- uCNC/src/core/io_control.c
- uCNC/src/core/io_control.h
- uCNC/src/interface/settings.c
- uCNC/src/interface/settings.h
-step enable settings implemented
> step enable settings implemented

- CHANGELOG.md
- README.md
- uCNC/cnc_config.h
- uCNC/cnc_hal_config.h
- uCNC/src/cnc_config_helper.h
- uCNC/src/core/io_control.c
- uCNC/src/core/parser.c
- uCNC/src/hal/boards/avr/boardmap_uno.h
- uCNC/src/hal/boards/samd21/boardmap_mzero.h
- uCNC/src/hal/boards/stm32/boardmap_blackpill.h
- uCNC/src/hal/boards/stm32/boardmap_bluepill.h
- uCNC/src/hal/mcus/avr/mcu_avr.c
- uCNC/src/hal/mcus/avr/mcumap_avr.h
- uCNC/src/hal/mcus/samd21/mcu_samd21.c
- uCNC/src/hal/mcus/samd21/mcumap_samd21.h
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f1x/mcumap_stm32f1x.h
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- uCNC/src/hal/mcus/stm32f4x/mcumap_stm32f4x.h
- uCNC/src/module.c
- uCNC/src/module.h
- uCNC/src/modules/bltouch.c
-modified servo pins for all cores to work with a tON range between 500us and 2500us
-bltouch implementation (initial)
> modified servo pins for all cores and implemented initial bltouch module

- CHANGELOG.md
- uCNC/cnc_config.h
- uCNC/src/interface/protocol.c
- uCNC/src/interface/serial.c
- uCNC/src/interface/serial.h
Output steps count on $P command print
> Output steps count on $P command print

- uCNC/src/hal/mcus/avr/mcumap_avr.h
- uCNC/src/module.c
- uCNC/src/modules/softuart.c
- uCNC/src/modules/softuart.h
-fix us delay function for AVR
-initial implementation of softuart (bit-banging)
> initial implementation of softuart (bit-banging)

- CHANGELOG.md
- uCNC/src/core/interpolator.c
- uCNC/src/core/io_control.c
fixed dirmask bug introduced with #148
> fixed dirmask bug

- uCNC/src/cnc_config_helper.h
- uCNC/src/core/interpolator.c
- uCNC/src/core/planner.h
Some buffer tweaks to allow buffer resizing on options file
> some buffer tweaks

- CHANGELOG.md
- uCNC/src/core/planner.c
fixed random angle error calculation between planner line segments that cause random speed drops
> fixed planner lines speed transition

- CHANGELOG.md
- uCNC/cnc_config.h
- uCNC/src/core/interpolator.c
- uCNC/src/core/planner.c
- uCNC/src/hal/kinematics/kinematic_cartesian.h
- uCNC/src/utils.h
-fixed some compilation flag options errors
> fixed some compilation flag options errors

- CHANGELOG.md
- uCNC/src/core/motion_control.c
- uCNC/src/core/motion_control.h
- uCNC/src/core/planner.c
- improved subsegment planner computations by skipping junction speed calculations after initial calculation for first subsegment
- fixed unit vector calculation in motion control line function
> improved subsegment planner computations

- CHANGELOG.md
- platformio.ini
- uCNC/cnc_config.h
- uCNC/cnc_hal_config.h
- uCNC/src/core/io_control.c
- uCNC/src/hal/boards/avr/boardmap_rambo14.h
- uCNC/src/hal/boards/avr/boardmap_ramps14.h
- uCNC/src/hal/boards/avr/boardmap_uno.h
- uCNC/src/hal/boards/avr/boardmap_x_controller.h
- uCNC/src/hal/boards/boarddefs.h
- uCNC/src/hal/boards/boards.h
- uCNC/src/hal/boards/samd21/boardmap_mzero.h
- uCNC/src/hal/boards/samd21/boardmap_zero.h
- uCNC/src/hal/boards/stm32/boardmap_blackpill.h
- uCNC/src/hal/boards/stm32/boardmap_bluepill.h
- uCNC/src/hal/boards/stm32/boardmap_mks_robin_nano_v1_2.h
- uCNC/src/interface/settings.c
added inventables x-controller board
added emergency stop logic invert option on main config file
fixed tmc soft uart input pins
moved pin pullup configuration to hal_config file
> added x-controller board and configurable emergency stop to config

- uCNC/src/cnc_config_helper.h
-more flexible DSS to allow very low feed speeds
> Enable bigger DSS values for 32bit bresenham

- uCNC/src/cnc.c
- uCNC/src/core/interpolator.c
- uCNC/src/core/parser.c
> Fix sticky jog

- .vscode/launch.json
- CHANGELOG.md
- uCNC/src/cnc.c
- uCNC/src/cnc.h
- uCNC/src/core/motion_control.c
- uCNC/src/core/parser.c
- uCNC/src/core/parser.h
- uCNC/src/core/planner.c
- uCNC/src/core/planner.h
- uCNC/src/interface/grbl_interface.h
- uCNC/src/interface/protocol.c
- uCNC/src/interface/serial.c
- uCNC/src/interface/serial.h
-implemented report status mask
-fix parser stored coordinates with coordinate offset command making next motion command with implicit target position to make unexpected motion path.
> implemented report status mask

- .vscode/launch.json
- CHANGELOG.md
- uCNC/src/core/parser.c
$G $P $I and $# system command now execute even if machine is not IDLE
> $G $P $I and $# executes without IDLE

- CHANGELOG.md
- uCNC/cnc_config.h
- uCNC/src/cnc.c
-  automatic status report available via option
> added automatic status report option

- .vscode/launch.json
- CHANGELOG.md
- uCNC/src/cnc.c
- uCNC/src/cnc_hal_config_helper.h
- uCNC/src/core/io_control.c
- uCNC/src/core/motion_control.c
- uCNC/src/hal/mcus/virtual/mcumap_virtual.h
- uCNC/src/interface/protocol.c
- redesigned dual limits detection
- all non dual axis limits are merged to allow axis colision (min and max)
> redesigned dual limits detection

- uCNC/cnc_hal_config.h
- uCNC/src/hal/tools/tools/spindle_pwm.c
- uCNC/src/hal/tools/tools/spindle_relay.c
Hi @Paciente8159.
Here's a simple change which adds a "relay spindle" which turns on and off digital pins when the spindle or coolant is enabled.
> Add relay spindle

- CHANGELOG.md
- uCNC/src/interface/settings.c
- partially revert #163 to allow setting $7 to also invert ESTOP
> partially-revert-163

- CHANGELOG.md
- uCNC/src/cnc_hal_config_helper.h
- uCNC/src/core/io_control.c
- added filter to invert control settings to prevent inverting undefined pins and turning on the alarm
> added filter to invert control setting

- uCNC/src/core/parser.c
> fixed G49 not working

- CHANGELOG.md
- makefiles/virtual/uCNC.dev
- uCNC/src/core/parser.c
- added support for G10 L20 (offset coordinate system relative to current position)
> G10 l20 support

- CHANGELOG.md
- uCNC/src/hal/tools/tools/spindle_besc.c
Added example for BESC spindle.
Have no way of testing for now (mainly the arm code)
> added example for BESC spindle

- CHANGELOG.md
- uCNC/src/core/io_control.c
- fix tool not stopping on ESTOP
> fix tool not stopping on ESTOP

- CHANGELOG.md
- uCNC/src/cnc.c
- force motion systems to sync on reset
> motion systems unsync after ESTOP

- CHANGELOG.md
- uCNC/src/hal/boards/avr/boardmap_ramps14.h
- uCNC/src/modules/parser_m42.c
- updated M42 to reflect current HAL IO convention
- added SERVO pin configs to ramps boardmap
> updated M42

- CHANGELOG.md
- uCNC/src/interface/protocol.c
- updated $P status report to reflect current HAL IO
> updated $P status report

- CHANGELOG.md
- uCNC/src/hal/tools/tools/spindle_besc.c
improved BESC spindle control with added default values for throttle down, neutral and full positions
added power relay control pin to turn spindle on and off
> Improved besc spindle

- CHANGELOG.md
- uCNC/cnc_hal_config.h
- uCNC/src/hal/tools/tools/spindle_besc.c
-improved BESC tool range calculation
> improved BESC tool range calculation

- uCNC/cnc_hal_config.h
- uCNC/src/core/interpolator.c
- uCNC/src/core/interpolator.h
- uCNC/src/hal/tools/tool.c
- uCNC/src/hal/tools/tool.h
- uCNC/src/hal/tools/tools/laser.c
- uCNC/src/hal/tools/tools/spindle_besc.c
- uCNC/src/hal/tools/tools/spindle_pwm.c
- uCNC/src/hal/tools/tools/spindle_relay.c
- uCNC/src/interface/protocol.c
- redesigned tool speed feedback. Tool now reports directly to protocol
- removed deprecated code
> redesigned tool speed feedback

- uCNC/src/core/parser.c
- fix G28-G30 not updating position
> fix G28-G30 not updating parser position

- platformio.ini
- uCNC/cnc_config.h
- uCNC/cnc_hal_config.h
- uCNC/src/cnc.c
- uCNC/src/cnc.h
- uCNC/src/cnc_hal_config_helper.h
- uCNC/src/core/interpolator.c
- uCNC/src/hal/boards/avr/boardmap_ramps14_mirror.h
- uCNC/src/hal/boards/boarddefs.h
- uCNC/src/hal/boards/boards.h
- uCNC/src/hal/mcus/avr/mcu_avr.c
- uCNC/src/hal/mcus/avr/mcumap_avr.h
- uCNC/src/interface/protocol.c
- uCNC/src/modules/encoder.c
- uCNC/src/modules/encoder.h
- fix missing EIMSK setting that prevented ISR from firing on INT trigger.
- added new mirror board that can be used to connect to an other board and act a position monitor
> Stepper encoder

- CHANGELOG.md
- uCNC/cnc_hal_config.h
- uCNC/src/hal/kinematics/kinematic_cartesian.c
- uCNC/src/hal/kinematics/kinematic_corexy.c
- uCNC/src/hal/kinematics/kinematic_delta.c
- option to disable homing on each individual axis
> Disable per axis homing

- uCNC/cnc_hal_config.h
- uCNC/src/cnc_hal_config_helper.h
- uCNC/src/core/io_control.c
-self squaring optional with dual-drive
> self squaring optional with dual-drive

- CHANGELOG.md
- platformio.ini
- uCNC/cnc_config.h
- uCNC/cnc_hal_config.h
- uCNC/src/cnc.c
- uCNC/src/cnc.h
- uCNC/src/cnc_hal_config_helper.h
- uCNC/src/core/interpolator.c
- uCNC/src/core/io_control.c
- uCNC/src/core/motion_control.c
- uCNC/src/hal/boards/avr/boardmap_ramps14_mirror.h
- uCNC/src/hal/boards/boarddefs.h
- uCNC/src/hal/boards/boards.h
- uCNC/src/hal/kinematics/kinematic_cartesian.c
- uCNC/src/hal/kinematics/kinematic_corexy.c
- uCNC/src/hal/kinematics/kinematic_delta.c
- uCNC/src/hal/mcus/avr/mcu_avr.c
- uCNC/src/hal/mcus/avr/mcumap_avr.h
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- uCNC/src/hal/mcus/virtual/mcumap_virtual.h
- uCNC/src/interface/protocol.c
- uCNC/src/modules/encoder.c
- uCNC/src/modules/encoder.h
Limits, Controls, Inputs and Probe redesigned ISR callbacks.
The ISR callback now runs the code to check for input changes and trigger the appropriate responses.
This attempts to make the behavior for inputs change more uniform and predictable (via ISR or softpolling).
> Redesign inputs ISR

- CHANGELOG.md
- uCNC/cnc_config.h
- uCNC/src/hal/mcus/avr/mcu_avr.c
- uCNC/src/hal/mcus/avr/mcumap_avr.h
- fixed input ISR detection on AVR that cause fault reset (introduced with (#213)
> fixed input ISR on AVR

- CHANGELOG.md
- uCNC/cnc_config.h
- uCNC/src/interface/defaults.h
- uCNC/src/interface/settings.c
- uCNC/src/interface/settings.h
- redesigned settings and struct default initialization
- added option for settings in RAM only
> redesigned settings

- CHANGELOG.md
- uCNC/cnc_config.h
- uCNC/src/core/parser.c
-added option to store G92 on non volatile to prevent EEPROM wear
> added option to store G92 on non volatile

- platformio.ini
- uCNC/src/hal/boards/.gitignore
- uCNC/src/hal/boards/avr/avr.ini
- uCNC/src/hal/boards/avr/bluepill_debug_cmsis_dap.cfg
- uCNC/src/hal/boards/avr/bluepill_debug_stlink.cfg
- uCNC/src/hal/boards/samd21/arduino_zero_debug.cfg
- uCNC/src/hal/boards/samd21/boardmap_zero.h
- uCNC/src/hal/boards/samd21/samd21.ini
- uCNC/src/hal/boards/stm32/stm32.ini
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- platformio multifile
- arduino zero boardmap based on arduino M0
> platformio multifile

- CHANGELOG.md
- uCNC/src/module.h
- Fixed multiple event declaration warnings caused after changes made by #234
> Fixed multiple event declaration warnings

- CHANGELOG.md
- uCNC/src/core/io_control.c
- uCNC/src/core/io_control.h
- added new io_control event to allow adding IO expansion modules (output IO mainly)
> added new io_control event

- CHANGELOG.md
- uCNC/src/hal/boards/avr/boardmap_ramps14.h
- uCNC/src/hal/mcus/mcu.h
- added mcu_nop macro
- fixed pin redefinition warning on AVR
> added mcu_nop macro

- CHANGELOG.md
- uCNC/src/hal/mcus/avr/mcu_avr.c
- uCNC/src/hal/mcus/esp32/mcu_esp32.c
- uCNC/src/hal/mcus/esp8266/mcu_esp8266.c
- uCNC/src/hal/mcus/lpc176x/mcu_lpc176x.c
- uCNC/src/hal/mcus/samd21/mcu_samd21.c
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- uCNC/src/interface/serial.c
moved activity led code to core
> moved activity led code to core

- uCNC/src/hal/boards/esp32/esp32.ini
- uCNC/src/hal/mcus/esp32/esp32_uart.cpp
- uCNC/src/hal/mcus/esp8266/esp8266_uart.cpp
- better wifi client detection and info messages
> better WiFi client detection

- uCNC/src/cnc.c
- uCNC/src/hal/boards/avr/boardmap_ramps14.h
- prevent dotask event lockup/stack overflow because of reentrancy
- added definitions to ramps SPI pinout
> prevent dotask event lockup

- uCNC/src/hal/mcus/avr/mcu_avr.c
- uCNC/src/hal/mcus/avr/mcumap_avr.h
- uCNC/src/hal/mcus/esp32/esp32_spi.cpp
- uCNC/src/hal/mcus/esp32/mcumap_esp32.h
- uCNC/src/hal/mcus/esp8266/esp8266_spi.cpp
- uCNC/src/hal/mcus/esp8266/mcumap_esp8266.h
- uCNC/src/hal/mcus/lpc176x/mcu_lpc176x.c
- uCNC/src/hal/mcus/mcu.h
- uCNC/src/hal/mcus/samd21/mcu_samd21.c
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f1x/mcumap_stm32f1x.h
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- uCNC/src/hal/mcus/stm32f4x/mcumap_stm32f4x.h
- added SPI speed config function
- replaced SPI_SPEED by SPI_FREQ in STM32 to match other MCUs
> added SPI speed config function

- uCNC/src/hal/boards/avr/boardmap_ramps14.h
- uCNC/src/modules/softi2c.c
- uCNC/src/modules/softi2c.h
- I2C functions reduces to 2 functions
> I2C re-write

- uCNC/src/core/motion_control.c
Fix dwell not synched. Dwell would execute out of time (async)
> Fix dwell not synched

- uCNC/src/core/interpolator.c
- modified itp_sync condition to prevent sync lockup
> modified itp_sync condition

- uCNC/src/core/interpolator.c
- fixed M4 laser mode  scaling factor (relative to programmed feed rate)
> fixed M4 laser mode  scaling factor

- uCNC/src/hal/mcus/avr/mcu_avr.c
- new AVR additional var to retain original servo value
> AVR additional var to retain original servo value

- uCNC/src/core/parser.c
- added support for ';' started comments
> Added support for ';' started comments

- uCNC/src/interface/protocol.c
- uCNC/src/interface/protocol.h
- uCNC/src/utils.h
- added module extension info event to allow extension modules to announce extra capabilities
> added module extension info event

- uCNC/src/hal/mcus/avr/mcumap_avr.h
- uCNC/src/hal/mcus/esp32/esp32_uart.cpp
- uCNC/src/hal/mcus/esp32/mcu_esp32.c
- uCNC/src/hal/mcus/esp32/mcumap_esp32.h
- uCNC/src/hal/mcus/esp8266/esp8266_uart.cpp
- uCNC/src/hal/mcus/esp8266/mcu_esp8266.c
- uCNC/src/hal/mcus/esp8266/mcumap_esp8266.h
- uCNC/src/hal/mcus/lpc176x/mcu_lpc176x.c
- uCNC/src/hal/mcus/lpc176x/mcumap_lpc176x.h
- uCNC/src/hal/mcus/mcu.c
- uCNC/src/hal/mcus/mcu.h
- uCNC/src/hal/mcus/samd21/mcu_samd21.c
- uCNC/src/hal/mcus/samd21/mcumap_samd21.h
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f1x/mcumap_stm32f1x.h
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- uCNC/src/hal/mcus/stm32f4x/mcumap_stm32f4x.h
- uCNC/src/hal/mcus/virtual/mcumap_virtual.h
- uCNC/src/modules/softi2c.h
- uCNC/src/modules/softuart.h
- new general solution for us_delay on ARM that does not depend on CoreDebug or ISR
- supports delays at least up to 500µs
> New general solution for soft delays based on loops

- uCNC/src/hal/tools/tools/vfd.c
- uCNC/src/interface/serial.c
- uCNC/src/interface/serial.h
- uCNC/src/modules/modbus.c
- Added support for Powtran 8100 VFD (basic support)
- modified VFD startup code to prevent locks if no connection available
> Added support for Powtran 8100 VFD

- uCNC/src/core/motion_control.c
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- fixed STM32 PROBE ISR triggering
- fixed soft detection if ISR not enabled
> fixed PROBE ISR for STM32

- uCNC/src/core/motion_control.c
- uCNC/src/hal/mcus/virtual/mcu_virtual.c
- uCNC/src/hal/mcus/virtual/mcumap_virtual.h
- uCNC/src/interface/settings.c
- fixed $ settings error for group settings (example steps per mm)
- motion control prevent error on linear motion of distance 0
- fixed virtual simulator compilation errors
> fixed $ settings error

- uCNC/src/module.c
- Added entry for modules loaded via web config tool
> Added entry for modules loaded via web config tool

- uCNC/cnc_config.h
- uCNC/src/cnc_hal_config_helper.h
- uCNC/src/core/interpolator.c
- uCNC/src/core/interpolator.h
- uCNC/src/core/io_control.c
- uCNC/src/core/motion_control.c
- uCNC/src/core/motion_control.h
- uCNC/src/core/planner.c
- uCNC/src/core/planner.h
- uCNC/src/hal/kinematics/kinematic_delta.h
- uCNC/src/hal/kinematics/kinematic_linear_delta.h
- uCNC/src/hal/kinematics/kinematicdefs.h
- uCNC/src/hal/mcus/virtual/mcumap_virtual.h
- fixed feed calculations for non linear kinematics
- fixed feed feedback for non linear kinematics
> Modified feed calculations

- uCNC/src/hal/mcus/esp32/mcu_esp32.c
- fixed timer errors on initialization with compilation via PIO
- fixed one shot timer ISR reseting
> fixed timer errors on init with PIO

- uCNC/src/core/motion_control.c
- resets motion block max_accel after each line
- initialize motion block on motion control homing
> resets motion block max_accel after each line

- uCNC/src/core/parser.c
- uCNC/src/hal/mcus/avr/mcu_avr.c
- uCNC/src/hal/mcus/esp32/mcu_esp32.c
- uCNC/src/hal/mcus/lpc176x/mcu_lpc176x.c
- uCNC/src/hal/mcus/mcu.h
- uCNC/src/hal/mcus/samd21/mcu_samd21.c
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- removed deprecated reference to servo pin offset and fixed internal µCNC offset for all architectures
> fixed reference to servo pin offset

- uCNC/cnc_config.h
- uCNC/src/interface/defaults.h
- uCNC/src/interface/settings.c
This is just a draft. I was wondering if these default options could be configurable for a specific machine.
> set default configuration options

- platformio.ini
- uCNC/cnc_config.h
- uCNC/src/hal/boards/rp2040/boardmap_rpi_pico_w.h
- uCNC/src/hal/boards/rp2040/rp2040.ini
- uCNC/src/hal/mcus/mcu.c
- uCNC/src/hal/mcus/rp2040/mcumap_rp2040.h
- uCNC/src/hal/mcus/rp2040/rp2040_arduino.cpp
- added Bluetooth connection to RP2040 (Pico W)
- added dummy extended mcu commands to mcu.c
- added ENABLE_BLUETOOTH to config.h
- removed forced ENABLE_WIFI from pico W boardmap
> RP2040 Bluetooth working

- uCNC/cnc_config.h
- uCNC/src/cnc_build.h
- uCNC/src/hal/boards/avr/boardmap_rambo14.h
- uCNC/src/hal/boards/avr/boardmap_ramps14.h
- uCNC/src/hal/boards/avr/boardmap_ramps14_mirror.h
- uCNC/src/hal/boards/avr/boardmap_uno.h
- uCNC/src/hal/boards/esp32/boardmap_mks_dlc32.h
- uCNC/src/hal/boards/esp32/boardmap_mks_tinybee.h
- uCNC/src/hal/boards/esp32/boardmap_wemos_d1_r32.h
- uCNC/src/hal/boards/esp8266/boardmap_wemos_d1.h
- uCNC/src/hal/boards/lpc176x/boardmap_re_arm.h
- uCNC/src/hal/boards/rp2040/boardmap_rpi_pico.h
- uCNC/src/hal/boards/samd21/boardmap_mzero.h
- uCNC/src/hal/boards/stm32/boardmap_blackpill.h
- uCNC/src/hal/boards/stm32/boardmap_bluepill.h
- uCNC/src/hal/boards/stm32/boardmap_mks_robin_nano_v1_2.h
-Enabled RX PULLUP on all boards with UART to prevent random noise picking
> Enabled RX PULLUP on all boards

- uCNC/src/hal/mcus/lpc176x/mcumap_lpc176x.h
- uCNC/src/hal/mcus/samd21/mcumap_samd21.h
- uCNC/src/hal/mcus/stm32f1x/mcumap_stm32f1x.h
- uCNC/src/hal/mcus/stm32f4x/mcumap_stm32f4x.h
-reviewed TinyUSB related macros on all MCU
> reviewed TinyUSB related macros on all MCU

- uCNC/src/hal/boards/lpc176x/boardmap_skr_v14_turbo.h
- uCNC/src/hal/mcus/lpc176x/mcumap_lpc176x.h
- added missing UART configurations for LPC176x
- SKR Turbo serial to Wifi options
> SKR Turbo serial to Wifi options

- uCNC/src/hal/boards/lpc176x/boardmap_skr_v14_turbo.h
- uCNC/src/hal/boards/lpc176x/lpc176x.ini
- uCNC/src/hal/mcus/lpc176x/lpc176x_usb.cpp
- uCNC/src/hal/mcus/lpc176x/mcu_lpc176x.c
- uCNC/src/hal/mcus/lpc176x/mcumap_lpc176x.h
- to fix USB hang problem (flag USE_ARDUINO_CDC)
> use LPC Framework USB CDC

- uCNC/src/core/parser.c
- uCNC/src/core/parser.h
- uCNC/src/modules/tmcdriver.c
- added logic to handle undefined AXIS commands on TMC M codes
> TMC MCodes handles undefined axis

- uCNC/src/modules/system_menu.c
- uCNC/src/modules/system_menu.h
- system menu jog display axis realtime position
- renamed timeout arg in system menu to be more readable
- fixed jog command string initialization that caused random memory overflow errors
> system menu jog display axis realtime position

- uCNC/src/hal/mcus/lpc176x/lpc176x_arduino.cpp
- uCNC/src/hal/mcus/lpc176x/mcumap_lpc176x.h
- uCNC/src/hal/mcus/samd21/mcumap_samd21.h
- uCNC/src/hal/mcus/stm32f1x/mcumap_stm32f1x.h
- uCNC/src/hal/mcus/stm32f4x/mcumap_stm32f4x.h
- USB Tx ready available checks if device connected preventing UART Tx stalling
> USB Tx ready available checks if device connected

- uCNC/src/hal/boards/esp32/boardmap_mks_dlc32.h
- uCNC/src/hal/mcus/esp32/esp32_arduino.cpp
- uCNC/src/hal/mcus/esp8266/esp8266_uart.cpp
- uCNC/src/hal/mcus/rp2040/rp2040_arduino.cpp
- uCNC/src/interface/settings.c
- uCNC/src/interface/settings.h
- added wifi IP identify command
- fixed MKS_DLC32 SPI pinout
- modified settings extension address checking
> new wifi IP command

- uCNC/src/hal/boards/esp32/esp32.ini
- uCNC/src/hal/mcus/esp32/esp32_arduino.cpp
- uCNC/src/hal/mcus/esp32/mcu_esp32.c
Added option to ESP32 EEPROM and SPI via Arduino to provide alternative if the custom implementations is not working on the board
> added ESP32 EEPROM and SPI via Arduino option

- uCNC/cnc_config.h
- uCNC/src/hal/mcus/esp32/esp32_arduino.cpp
- uCNC/src/hal/mcus/esp8266/esp8266_uart.cpp
- uCNC/src/hal/mcus/mcu.c
- uCNC/src/hal/mcus/mcu.h
- uCNC/src/hal/mcus/rp2040/mcumap_rp2040.h
- uCNC/src/hal/mcus/rp2040/rp2040_arduino.cpp
- Buffered wifi transmission on ESP32 ESP8266 and RPI2040 to improve wifi protocol transmission speed
- RP2040 still seems to drag
> Buffered wifi transmission

- uCNC/src/hal/boards/stm32/stm32.ini
- uCNC/src/hal/mcus/lpc176x/mcu_lpc176x.c
- uCNC/src/hal/mcus/rp2040/rp2040_arduino.cpp
- uCNC/src/hal/mcus/samd21/mcu_samd21.c
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
modified USB TX functions for:
- STM32 (tested and working)
- SAMD21 (tested and working)
- LPC17xx (partially tested and working)
- RP2040 (untested)
> modified USB TX functions

- uCNC/cnc_config.h
- uCNC/cnc_hal_config.h
- uCNC/src/hal/tools/tools/laser_pwm.c
- overridable LASER PWM MIN value
- updated some config comments
> overridable LASER PWM MIN value

- uCNC/cnc_hal_config.h
- uCNC/src/cnc.c
- uCNC/src/cnc_hal_config_helper.h
- uCNC/src/core/io_control.c
- uCNC/src/hal/boards/stm32/stm32.ini
- uCNC/src/hal/tools/tool.c
- uCNC/src/hal/tools/tool.h
- uCNC/src/hal/tools/tools/laser_ppi.c
- uCNC/src/hal/tools/tools/laser_pwm.c
- uCNC/src/hal/tools/tools/pen_servo.c
- uCNC/src/hal/tools/tools/plasma_thc.c
- uCNC/src/hal/tools/tools/spindle_besc.c
- uCNC/src/hal/tools/tools/spindle_pwm.c
- uCNC/src/hal/tools/tools/spindle_relay.c
- uCNC/src/hal/tools/tools/vfd_modbus.c
- uCNC/src/hal/tools/tools/vfd_pwm.c
- uCNC/src/interface/protocol.c
- uCNC/src/interface/protocol.h
- uCNC/src/interface/settings.c
- uCNC/src/interface/settings.h
- uCNC/src/module.c
- uCNC/src/module.h
- uCNC/src/modules/pid.c
- uCNC/src/modules/pid.h
- new PID module more flexible
- updated tools functions
- new easy settings macros
> new PID module and updated tools

- uCNC/cnc_config.h
- uCNC/src/cnc.c
- uCNC/src/utils.h
- added option to debug parsing execution times of commands
- minor fix in fast math macro
> added parsing debug message

- uCNC/cnc_hal_config.h
- uCNC/src/core/interpolator.c
- Set a custom filter that prevents step motions in realtime
> new RT_STEP_PREVENT_CONDITION condition

- uCNC/src/hal/tools/tools/plasma_thc.c
- uCNC/src/hal/tools/tools/vfd_pwm.c
- uCNC/src/interface/protocol.c
- uCNC/src/interface/protocol.h
- added status report extension callback
- added THC tool status report and THC extension report callback
> Status report extender

- makefiles/virtual/uCNC.dev
- uCNC/src/hal/tools/tools/plasma_thc.c
- added velocity anti-dive feature
- added similar linuxcnc M62-M65 THC enable control
> plasma thc tool update

- uCNC/cnc_hal_config.h
- uCNC/src/modules/tmcdriver.c
- modified TMC drivers to work with addressed mode
> modified TMC drivers to work with addressed mode

- uCNC/src/core/interpolator.c
- uCNC/src/hal/mcus/esp32/mcu_esp32.c
- fixed 74HC595 concurrency issues my moving softpwm to core1
- fixed step bug introduced by change in step ISR
> fixed 74HC595 concurrency issues

- uCNC/src/hal/mcus/esp8266/mcu_esp8266.c
- uCNC/src/hal/mcus/esp8266/mcumap_esp8266.h
- uCNC/src/hal/tools/tools/spindle_pwm.c
- uCNC/src/hal/tools/tools/vfd_pwm.c
- uCNC/src/modules/system_menu.c
- update ESP8266 mcumap
- fixed pwm tools assert pins
- fixed system menu compilation error with tool count 0
> update ESP8266 mcumap

- uCNC/src/core/interpolator.c
- fixed hold issue on version1.8 that keeps generating steps until the end of the motion
> fixed hold issue on version1.8

- uCNC/src/cnc.c
> fixed sticky RUN state after alarm

- uCNC/src/hal/boards/rp2040/boardmap_rpi_pico.h
- uCNC/src/hal/boards/rp2040/rp2040.ini
- uCNC/src/hal/mcus/rp2040/mcumap_rp2040.h
- fixed input and output read macros for RP2040
- fixed input changed ISR macro
> fixed input and output read macros for RP2040

- uCNC/src/cnc.c
- uCNC/src/core/parser.c
- uCNC/src/core/planner.c
- uCNC/src/core/planner.h
- uCNC/src/hal/tools/tools/laser_pwm.c
- modified reset login to improve software recognition of initial message
- modified speed overrides to reduce binary size to fit UNO
> Modified soft reset logic

- uCNC/src/cnc.c
- uCNC/src/core/parser.c
- uCNC/src/core/planner.c
- uCNC/src/core/planner.h
- uCNC/src/modules/system_menu.c
- uCNC/src/modules/system_menu.h
- modified soft reset to improve software controller startup message detection
- simplified override messages to reduce compilation size
- modified system menu to fix warnings
> modified soft reset and overrides

- uCNC/src/core/parser.c
- uCNC/src/interface/serial.c
- uCNC/src/interface/serial.h
- added option to set one port/stream as a DEBUG stream
> Debug stream

- uCNC/src/modules/system_menu.c
- fix var edit reseting boleans on exit edit
> fix var edit reseting boleans on exit edit

- uCNC/src/cnc.c
- uCNC/src/core/parser.c
- uCNC/src/hal/boards/avr/avr.ini
- uCNC/src/hal/mcus/virtual/mcu_virtual.c
- get parser position from parser_get_coordsys
- return origin if failed to load from eeprom
> Get parser position from parser_get_coordsys

- uCNC/src/cnc.c
fixed auto report compilation error (variable declared in the wrong place)
> fixed auto report compilation error

- uCNC/src/cnc.c
- uCNC/src/core/interpolator.c
- uCNC/src/core/parser.c
- uCNC/src/core/parser.h
- uCNC/src/hal/tools/tool.c
- uCNC/src/interface/protocol.c
- uCNC/src/interface/settings.c
- uCNC/src/interface/settings.h
- fixed instant speed from 0 (immediate acceleration)
- removed tool changing code with single tool to allow code to fit on UNO
> fixed instant speed from 0

- uCNC/src/core/parser.c
- uCNC/src/core/planner.c
- uCNC/src/core/planner.h
- uCNC/src/hal/tools/tool_helper.h
- fixed coolant pin control via M7 and M8
- removed deprecated mist pin assert
- fixed parser tool flags update mask
> fixed coolant pin control via M7 and M8

- uCNC/src/hal/mcus/esp32/mcu_esp32.c
- fixed ESP32 step rate with emulated PWM enabled
> fixed ESP32 step rate with emulated PWM

- uCNC/src/modules/softi2c.c
- uCNC/src/modules/softspi.c
- uCNC/src/modules/softuart.c
- added calls to main loop in soft emulated coms to prevent motion starving
> added calls to main loop in soft emulated coms

- uCNC/src/core/interpolator.c
- new interpolator algorithm for linear and s curve interpolation
- refactored s curve functions
- modified DSS to take in account step empty time samples
> new interpolator algorithm

- uCNC/src/core/parser.c
- fix jog flag being cleared while waiting for jog command to complete (introduced with #565)
> fix jog flag being cleared

- uCNC/cnc_config.h
- uCNC/src/core/motion_control.c
- modify soft limits violation via options to send error instead of alarm
- option to hold or continue on soft limit violation
> modify soft limits violation via options

- uCNC/src/cnc.c
- uCNC/src/module.h
- added flag to prevent event reentrancy (per external module)
- modified main loop event call order
> Modified module to prevent reentrancy

- uCNC/src/cnc.c
Fixed home motion flushing after homing resume (with or without error)
> Fixed home motion flushing after homing resume (with or without error)

- uCNC/src/cnc.c
- uCNC/src/core/parser.c
- uCNC/src/core/parser.h
- uCNC/src/hal/boards/avr/boardmap_uno.h
- uCNC/src/hal/mcus/avr/mcu_avr.c
- uCNC/src/hal/tools/tool.c
- uCNC/src/interface/protocol.c
- uCNC/src/interface/serial.c
- slight reduction of core code and AVR
- improved modal report for M7, M8 (now can display both)
> Reduce code for uno

- uCNC/src/interface/serial.c
- uCNC/src/interface/serial.h
added multistream parallel access guard option
> added multistream parallel access guard option

- uCNC/src/hal/mcus/esp8266/esp8266_arduino.cpp
- fixed ESP8266 wifi rx reading wrong buffer
> fixed ESP8266 wifi rx reading wrong buffer

- uCNC/src/module.h
- implements a circular event handler to improve even invoking and don't starve the events at the end of the queue
> circular default event handler

- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- uCNC/src/hal/mcus/stm32f4x/mcumap_stm32f4x.h
- STM32F4 SPI configuration AFIO fixed and checking
> STM32F4 SPI configuration AFIO fixed

- uCNC/src/hal/tools/tools/plasma_thc.c
- uCNC/src/hal/tools/tools/spindle_pwm.c
- uCNC/src/hal/tools/tools/vfd_pwm.c
- fixed range function for plasma thc
- fixed pid range calls on spindle pwm and vfd pwm
> fixed range function for plasma thc

- uCNC/src/interface/settings.c
- uCNC/src/interface/settings.h
- uCNC/src/module.h
- added new extension settings events to prevent event self calling problems and propagation problems caused by event handling (like the SD card module)
> Extended setting new events

- uCNC/src/hal/mcus/avr/mcu_avr.c
- uCNC/src/hal/mcus/esp32/mcu_esp32.c
- fixed UART2 detached callback
> fixed UART2 detached callback

- uCNC/src/core/parser.c
- fix RST cmd early execution and for to wait for the line to be terminated
> fix RST cmd early execution

- uCNC/src/cnc.c
- fix spindle restore (state lost) after a jog cancel
> fix spindle restore with jog cancel

- uCNC/src/cnc.c
- uCNC/src/cnc.h
- uCNC/src/core/motion_control.c
- fixed dwell to resume on alarm or error
> fixed dwell to resume on alarm or error

- uCNC/cnc_config.h
- uCNC/src/core/parser.c
- uCNC/src/interface/grbl_interface.h
- uCNC/src/interface/protocol.c
- uCNC/src/interface/protocol.h
- uCNC/src/interface/settings.c
- added additional grbl emulation level to fully emulate grbl startup and info messages and improve compatibility with older and strict software
> added additional Grbl emulation level

- uCNC/src/cnc_hal_config_helper.h
- uCNC/src/core/interpolator.c
- option to do limit checking inside step ISR
> option to do limit checking inside step ISR

- uCNC/src/hal/mcus/esp32/esp32_arduino.cpp
- uCNC/src/hal/mcus/esp8266/esp8266_arduino.cpp
- uCNC/src/hal/mcus/rp2040/rp2040_arduino.cpp
- uCNC/src/modules/endpoint.h
- added the ability to handle endpoints with wildcard in the end
> Endpoint end wildcard handler

- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- fixed STM32 I2C stop bit condition
> fixed STM32 I2C stop bit condition

- uCNC/src/hal/mcus/rp2040/mcu_rp2040.c
- uCNC/src/hal/mcus/rp2040/rp2040_arduino.cpp
- initialize EEPROM before wifi connection to allow proper wifi startup connection (saved parameters)
- removed duplicate local buffer for telnet connection
> fixed RP2040 wifi and telnet connection

- uCNC/src/hal/tools/tools/spindle_relay.c
- added missing range function to spindle relay tool
> Fix spindle relay tool

- uCNC/src/cnc.c
- uCNC/src/hal/mcus/mcu.c
- uCNC/src/hal/mcus/mcu.h
- add custom IO initialization code (overridable)
> add custom IO initialization code

- uCNC/src/core/interpolator.c
- fix deaccel bug if no deaccel frames are required
> Fix deaccel bug if no deaccel frames are required

- uCNC/src/core/motion_control.c
- uCNC/src/core/parser.c
- fix systems sync after HMap generation
- fix retraction between probings
> fix systems sync after HMap generation

- uCNC/src/modules/file_system.c
- fixed typo
- removed duplicate listener
> Fix file_system.c typo

- uCNC/src/core/motion_control.c
- uCNC/src/core/motion_control.h
- uCNC/src/core/parser.c
- fix G39 hmap reset compile error
> fix G39 hmap reset compile error

- uCNC/src/core/io_control.c
- uCNC/src/core/motion_control.c
- homing code optimization and cleaning
- fixed individual axis fetching distance to match 1.5x the axis size
- this opens the possibility to implement individual pulloff distances
> homing code optimization and cleaning

- uCNC/src/core/motion_control.c
- uCNC/src/core/parser.c
- uCNC/src/core/parser.h
- uCNC/src/hal/mcus/esp32/esp32_arduino.cpp
- uCNC/src/hal/mcus/esp8266/esp8266_arduino.cpp
- uCNC/src/hal/mcus/mcu.c
- uCNC/src/hal/mcus/mcu.h
- uCNC/src/hal/mcus/rp2040/rp2040_arduino.cpp
- merged custom grbl cmds and board grbl cmds
- prevent board custom commands from reading command arg if command is not targeted to it
- removed mcu HAL function to custom commands
- modified custom MCU commands for ESP32 ESP8266 and RP2040
> Merged custom Grbl commands and board custom Grbl commands logic

- uCNC/src/hal/mcus/esp32/esp32_arduino.cpp
- uCNC/src/hal/mcus/esp32/mcu_esp32.c
corrected configuration of SPI frequency and mode on ESP32 for both ESP-IDF and Arduino based versions
> ESP32 SPI configuration fixes

- uCNC/src/hal/boards/rp2040/boardmap_rpi_pico.h
- uCNC/src/hal/mcus/rp2040/rp2040_arduino.cpp
- RP2040 SPI bulk transfer
- some SPI fixes
This is just an Arduino SPI wrapper. A proper DMA capable version needs to be implemented
> RP2040 SPI bulk transfer

- uCNC/src/hal/mcus/esp32/esp32_arduino.cpp
- uCNC/src/hal/mcus/esp32/mcu_esp32.c
- uCNC/src/hal/mcus/esp8266/esp8266_arduino.cpp
- uCNC/src/hal/mcus/mcu.c
- uCNC/src/hal/mcus/mcu.h
- uCNC/src/hal/mcus/rp2040/rp2040_arduino.cpp
- uCNC/src/hal/mcus/samd21/mcu_samd21.c
- uCNC/src/modules/softspi.c
- uCNC/src/modules/softspi.h
- better SPI sharing by separation of hardware and software configurations and settings, and better busy state keeping
> better hard and soft SPI sharing

- uCNC/src/hal/mcus/esp32/esp32_arduino.cpp
- uCNC/src/hal/mcus/esp32/mcu_esp32.c
- uCNC/src/hal/mcus/esp8266/esp8266_arduino.cpp
- uCNC/src/hal/mcus/mcu.c
- uCNC/src/hal/mcus/rp2040/rp2040_arduino.cpp
- uCNC/src/hal/mcus/samd21/mcu_samd21.c
- uCNC/src/module.c
- uCNC/src/module.h
- uCNC/src/modules/softspi.c
- uCNC/src/modules/softspi.h
- New module resource guard to allow access locks to shared hardware and software resources
- Simplified/removed soft/hard SPI config struck and lock flags
> New module resource guard

- uCNC/src/modules/system_menu.c
- uCNC/src/modules/system_menu.h
- added function to be able to modify a renderer/action callback for any menu page
- added extensible action code handler
> Added new methods to system menu

- uCNC/src/modules/language/language_en.h
This PR adds a couple new entries in the language file. These are used in the Win9x theme of LVGL support module.
> Add more language file entries

- uCNC/src/core/io_control.c
- fixed missing digital pin readings for extended generic inputs
> fixed missing digital pin readings

- uCNC/src/interface/protocol.c
- updated pin state print to extended pins (DOUT/DIN 32 to 49)
> updated pin state print to extended pins

- uCNC/src/hal/boards/stm32/boardmap_mks_robin_nano_V3_1.h
- uCNC/src/hal/boards/stm32/boardmap_mks_robin_nano_v3_1.h
- uCNC/src/hal/boards/stm32/boardmap_srk_pro_v1_2.h
- uCNC/src/hal/boards/stm32/stm32.ini
- uCNC/src/hal/mcus/stm32f1x/mcu_stm32f1x.c
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- Custom clocks setup for STM32F4 boards
> Custom STM32f4 clocks

- uCNC/src/hal/mcus/mcu.h
- uCNC/src/modules/softspi.c
- fix softspi resources locking to allow distinction between SPI and SPI2
> fix softspi resources locking

- platformio.ini
- uCNC/src/hal/boards/avr/avr.ini
- uCNC/webconfig.ini
- ucnc_modules.py
- this adds a custom script to integrate modules in an automatic way using PIO
> Download script for modules via PIO

- uCNC/src/hal/boards/stm32/boardmap_mks_robin_nano_V3_1.h
- uCNC/src/hal/boards/stm32/boardmap_mks_robin_nano_v3_1.h
- uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c
- fix I2C pin alternate function config
> Fixed STM32F4 I2C pin AF config

- uCNC/src/interface/grbl_settings.c
Send error if trying to set invalid setting index. For example $250=20
> send error if trying to set invalid setting index

- .github/workflows/pio-build.yaml
- .github/workflows/pio-release.yaml
- .github/workflows/pio-test.yaml
- platformio.ini
- uCNC/webconfig.ini
- removed webconfig ini
- custom configs will now be done by replacing platformio.ini file
> removed webconfig ini

- uCNC/src/modules/softuart.c
- uCNC/src/utils.h
- fixed softuart getc to wait for the line to go idle
- modified timeout macro to allow negative parameters
> fixed softuart getc

- uCNC/src/modules/softuart.h
- fixed ONEWIRE emulated transmission (requires PP drive logic)
> fixed ONEWIRE emulated transmission

- uCNC/src/core/parser.c
- fixed canned cycle command feed and spindle update after running canned cycle
> fixed canned cycle command feed and spindle update

- uCNC/src/core/interpolator.c
- uCNC/src/hal/mcus/lpc176x/mcu_lpc176x.c
- uCNC/src/hal/mcus/lpc176x/mcumap_lpc176x.h
- modified LPC17xx step generation algorithm to prevent odd acceleration behavior when chaining multiple small linear commands
- improved step resolution on LPC17xx step ISR
- added small delay on interpolator to ensure minimal interval after the last step when the motion stops.
> Fix LPC17xx step generation

- uCNC/src/interface/grbl_settings.c
- uCNC/src/interface/grbl_settings.h
- fix incorrect settings var type print
- added settings var type macros to make code easier to read/write and prevent errors
> fix incorrect settings var type print

- uCNC/src/modules/softspi.c
- uCNC/src/modules/softspi.h
update spi port speed/mode correctly
> update spi port speed/mode correctly

- uCNC/src/hal/mcus/mcu.c
- uCNC/src/interface/grbl_print.c
- fixes integer array printing
> fixes integer array printing

- uCNC/src/core/parser.c
- uCNC/src/core/parser.h
- uCNC/src/module.h
- expose parser coordinate save function to allow modifications by modules
> expose parser coordinate save function

- uCNC/src/hal/kinematics/kinematic_rtheta.c
- uCNC/src/hal/kinematics/kinematic_rtheta.h
- uCNC/src/hal/kinematics/kinematicdefs.h
Integration of RTheta Kinematics added in #839
> Integration of Rtheta Kinematics

- uCNC/src/core/parser.c
Fix g28/g30 parsing and motion execution
> Fix g28/g30 parsing

- uCNC/src/interface/grbl_protocol.c
- fix settings array print (was printing only 1st element value)
> fix settings array print

- uCNC/src/core/io_control.c
- uCNC/src/core/io_control.h
- customizable IO conditions for special inputs (control pins, probe and limit pins)
> Customizable IO conditions for special inputs

- uCNC/cnc_config.h
- uCNC/src/core/parser.c
- allow settings in array format with option ALLOW_SETTINGS_ARRAY_FORMAT
> allow settings in array format
